linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (github.com/spf13/cobra.Command).Flags
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - fmt.Println

issues:
  exclude-rules:
    # Allow unchecked Close() in deferred calls
    - linters:
        - errcheck
      source: "defer .+\\.Close\\(\\)"
    # Allow unchecked errors in test files
    - path: _test\.go
      linters:
        - errcheck
    # Allow explicit error discards with _ =
    - linters:
        - errcheck
      source: "_ ="
